'use client';
import {Canvas,useFrame,useThree} from '@react-three/fiber';
import {OrbitControls} from '@react-three/drei';
import {useEffect,useRef} from 'react';
import {blocks} from './model';
import {createFrameGuard} from './performance';
const positions:[[number,number,number],[number,number,number],[number,number,number]]=[[12,8,14],[-13,7,11],[11,9,-13]];
function Camera({angle}:{angle:number}){const {camera,invalidate}=useThree();useEffect(()=>{camera.position.set(...positions[angle]);camera.lookAt(0,.8,0);invalidate()},[angle,camera,invalidate]);return null}
function Monitor({active,onSlow}:{active:boolean;onSlow:()=>void}){const guard=useRef(createFrameGuard());useEffect(()=>{guard.current.reset()},[active]);useFrame((state,delta)=>{if(active&&guard.current.sample(delta))onSlow()});return null}
export default function Scene({angle,hour,active,onSlow,onReady}:{angle:number;hour:number;active:boolean;onSlow:()=>void;onReady:()=>void}){return <Canvas shadows dpr={[1,1.35]} frameloop={active?'always':'demand'} camera={{position:[12,8,14],fov:38,near:.1,far:100}} gl={{antialias:true,powerPreference:'low-power'}} onCreated={({gl})=>{gl.domElement.addEventListener('webglcontextlost',onSlow,{once:true});onReady()}} fallback={<span>Vue statique disponible.</span>}><color attach="background" args={['#f0f0ec']}/><ambientLight intensity={1.1}/><directionalLight position={[hour===0?8:-7,10,hour===0?5:-2]} intensity={2.5} castShadow shadow-mapSize={[1024,1024]} shadow-camera-left={-12} shadow-camera-right={12} shadow-camera-top={12} shadow-camera-bottom={-12} shadow-bias={-.001}/><group>{blocks.map((b,i)=><mesh key={i} position={b.p} castShadow receiveShadow><boxGeometry args={b.s}/><meshStandardMaterial color={b.c||'#c2c1bb'} roughness={.9}/></mesh>)}</group><mesh rotation={[-Math.PI/2,0,0]} position={[0,-.75,0]} receiveShadow><planeGeometry args={[200,200]}/><meshStandardMaterial color="#f0f0ec" roughness={1}/></mesh><OrbitControls makeDefault target={[0,.8,0]} enablePan={false} enableZoom={false} minPolarAngle={.3} maxPolarAngle={1.48} rotateSpeed={.55} enableDamping dampingFactor={.09}/><Camera angle={angle}/><Monitor active={active} onSlow={onSlow}/></Canvas>}
