'use client';
import {useState} from 'react';
import Viewer from '@/components/monolithe/Viewer';
import Plan from '@/components/monolithe/Plan';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
export default function Home(){const [contact,setContact]=useState(false);return <><main><section id="hero" className="hero"><header><a href="#hero" className="logo">M<span>ATELIER<br/>MONOLITHE</span></a><a className="discreet" href="#contact">Un projet ? ↗</a></header><div className="hero-heading"><h1>Atelier Monolithe</h1><p>Architecture. Marseille.</p></div><Viewer/><div className="hero-caption"><span>Faites pivoter le projet.</span><a href="#villa">Explorer le projet <span>↓</span></a></div><nav className="project-nav" aria-label="Navigation par projet"><a href="#villa"><span>01</span> Villa Cassis <small>2025</small></a><a href="#arts"><span>02</span> Maison des Arts <small>2023</small></a><a href="#vieux-port"><span>03</span> Extension Vieux-Port <small>2022</small></a></nav></section>
<section id="cabinet" className="cabinet section"><div className="section-label">01 — LE CABINET</div><div className="cabinet-layout"><div><h2>Construire des volumes qui durent</h2><p>Atelier Monolithe conçoit des bâtiments qui assument leur masse — béton brut, lignes nettes, peu de concessions au décoratif. Le cabinet travaille sur des projets résidentiels et culturels, principalement dans le sud de la France, avec une conviction : la matière bien employée n'a pas besoin d'ornement.</p></div><img src="/photos/07.webp" alt="L'équipe d'Atelier Monolithe étudie un plan sur chantier — visuel de démonstration" loading="lazy" width="1600" height="900"/></div></section>
<section id="villa" className="feature section"><div className="section-label">02 — PROJET PHARE</div><div className="feature-heading"><h2>Villa Cassis</h2><div><p>Une résidence privée construite à flanc de colline, pensée comme un seul bloc de béton posé dans le paysage. Le projet est explorable en 3D ci-dessus — faites-le pivoter pour voir comment la lumière traverse les volumes selon l'heure.</p><p className="spec">Surface : 320 m² · Livraison : 2025 · Lieu : Cassis</p></div></div><img className="feature-main" src="/photos/01.webp" alt="Villa Cassis, volume de béton dans le paysage méditerranéen — visuel de démonstration" loading="lazy" width="1600" height="900"/><div className="feature-pair"><img src="/photos/02.webp" alt="Villa Cassis, patio et façade arrière" loading="lazy" width="1600" height="900"/><img src="/photos/03.webp" alt="Villa Cassis, intérieur ouvert sur la mer" loading="lazy" width="1600" height="900"/></div><div className="plan-row"><span>VILLA CASSIS<br/>320 M² / 2025</span><Plan/></div></section>
<section id="projets" className="projects section"><div className="section-label">03 — SÉLECTION</div><h2>Réalisations</h2><div className="project-list"><article><a href="#villa"><img src="/photos/01.webp" alt="Villa Cassis" loading="lazy" width="1600" height="900"/><h3>Villa Cassis — Résidentiel · Cassis · 2025 <span>↗</span></h3></a></article><article id="arts"><img src="/photos/04.webp" alt="Maison des Arts, façade de béton à Marseille" loading="lazy" width="1600" height="900"/><h3>Maison des Arts — Culturel · Marseille · 2023</h3><img className="secondary-project" src="/photos/05.webp" alt="Maison des Arts, espace culturel intérieur" loading="lazy" width="1600" height="900"/></article><article id="vieux-port"><img src="/photos/06.webp" alt="Extension contemporaine d'une maison du Vieux-Port" loading="lazy" width="1600" height="900"/><h3>Extension Vieux-Port — Résidentiel · Marseille · 2022</h3></article></div></section>
<section id="approche" className="approach section"><div className="section-label">04 — APPROCHE</div><div className="approach-heading"><h2>Comment on travaille</h2><p>Chaque projet démarre par une lecture du site — orientation, lumière, contraintes. Le béton, le verre et l'acier sont choisis pour ce qu'ils permettent structurellement, pas pour l'effet. La modélisation 3D accompagne le projet du premier croquis à la livraison.</p></div><div className="technical"><Plan kind={1}/><Plan kind={2}/></div></section>
<section id="contact" className="contact section"><div className="section-label">05 — CONTACT</div><h2>Un projet ?</h2><p>Atelier Monolithe étudie un nombre limité de projets par an, pour garder le temps de bien faire.</p><button onClick={()=>setContact(true)}>Nous écrire <span>↗</span></button></section></main><footer><span>ATELIER MONOLITHE</span><p>Concept créé par Megahana — marque fictive à des fins de démonstration.</p><a href="#hero">Haut de page ↑</a></footer><Dialog open={contact} onOpenChange={setContact}><DialogContent className="contact-dialog"><DialogTitle>Nous écrire</DialogTitle><DialogDescription>Atelier Monolithe est un cabinet fictif. Aucun message ne peut être envoyé depuis cette démonstration.</DialogDescription><button className="close-contact" onClick={()=>setContact(false)}>Revenir au site</button></DialogContent></Dialog></>}
